// <auto-generated />
using LibraryAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryAPI.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20230116102547_CreateInitial")]
    partial class CreateInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryAPI.Models.Akun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BukuId")
                        .HasColumnType("int");

                    b.Property<string>("Nama_belakang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama_depan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BukuId");

                    b.ToTable("Akuns");
                });

            modelBuilder.Entity("LibraryAPI.Models.Buku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Deskripsi_buku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gambar_buku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kategori_buku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama_buku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Penulis_buku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status_buku")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("bukus");
                });

            modelBuilder.Entity("LibraryAPI.Models.Akun", b =>
                {
                    b.HasOne("LibraryAPI.Models.Buku", "Buku")
                        .WithMany("Akuns")
                        .HasForeignKey("BukuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buku");
                });

            modelBuilder.Entity("LibraryAPI.Models.Buku", b =>
                {
                    b.Navigation("Akuns");
                });
#pragma warning restore 612, 618
        }
    }
}
